apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gke/manifests/db-ss.yaml
- gke/manifests/dbconfig.yaml
- gke/manifests/deployment.yaml
- gke/manifests/gke-secret.yaml
- gke/manifests/ingress.yaml
- gke/manifests/persistentvolumeclaim.yaml
- gke/manifests/service.yaml
- gke/manifests/wikipedia-cronjob.yaml
images:
- name: PROJECT/IMAGE
  newName: heseduud/gkeproject