apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: project-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      volumes:
        - name: project-pvolume
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: project-backend
          image: heseduud/projectbackend:2.08
          volumeMounts:
            - name: project-pvolume
              mountPath: /usr/src/app/files
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: project-dbconfig
                  key: postgres_hostaddr
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: project-dbconfig
                  key: postgres_user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: project-dbconfig
                  key: postgres_db
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: project-dbconfig
                  key: project_db_port