apiVersion: v1
kind: Service
metadata:
  namespace: applications
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3002