apiVersion: v1
kind: Service
metadata:
  name: kubecrud-svc
spec:
  type: NodePort
  selector:
    app: kubecrud
  ports:
  - name: http
    nodePort: 30080
    protocol: TCP
    port: 1234
    targetPort: 5000
