apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecrud-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecrud
  template:
    metadata:
      labels:
        app: kubecrud
    spec:
      containers:
        - name: kubecrud
          image: heseduud/kubecrud