apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: applications
  name: mainapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      containers:
        - name: mainapp
          image: heseduud/mainapp:4.01v3
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          envFrom:
          - configMapRef:
              name: env-configmap
