name: Delete namespace on branch deletion

on:
  delete:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    name: Delete namespace
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Delete namespace
      run: |-
        echo "Deleting namespace: ${{ github.event.ref }}"
        kubectl delete namespace ${{ github.event.ref }}